version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "43306:3306"
    env_file: .docker_env
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/aws_console_beta
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .docker_env