version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.6.0
  aws-ecs: circleci/aws-ecs@1.0.4
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'aws-console-beta'
          tag: '${CIRCLE_SHA1}'
          extra-build-args: '--build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY} --build-arg RAILS_ENV=${RAILS_ENV}'

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'task-aws-console-beta'
          cluster-name: 'cl-aws-console-beta'
          service-name: 'service-aws-console-beta'
          container-image-name-updates: 'container=container-aws-console-beta,tag=${CIRCLE_SHA1}'

      - rails-db-create:
          requires:
            - aws-ecs/deploy-service-update
          machine:
            image: ubuntu-1604:201903-01
            steps:
              - checkout
              - run:
                  name: Create Database
                  command: rails db:create