version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.6.0
  aws-ecs: circleci/aws-ecs@1.0.4
  aws-cli: circleci/aws-cli@0.1.19

executors:
  container:
    docker:
      - image: "${AWS_ECR_ACCOUNT_URL}/aws-console-beta"

jobs:
  db-create-migrate-on-task-run:
    executor: container
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: "db create"
          command: |
            aws ecs run-task --region $AWS_REGION \
              --cluster cl-aws-console-beta \
              --task-definition task-aws-console-beta \
              --overrides '{ "containerOverrides": [ { "command": ["rails", "db:create"] } ] }'
      - run:
          name: "db migrate"
          command: |
            aws ecs run-task --region $AWS_REGION \
              --cluster cl-aws-console-beta \
              --task-definition task-aws-console-beta \
              --overrides '{ "containerOverrides": [ { "command": ["rails", "db:migrate"] } ] }'

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'aws-console-beta'
          tag: '${CIRCLE_SHA1}'
          extra-build-args: '--build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY} --build-arg RAILS_ENV=${RAILS_ENV}'

      - db-create-migrate-on-task-run:
          requires:
            - aws-ecr/build-and-push-image

      - aws-ecs/deploy-service-update:
          requires:
            - db-create-migrate-on-task-run
          family: 'task-aws-console-beta'
          cluster-name: 'cl-aws-console-beta'
          service-name: 'service-aws-console-beta'
          container-image-name-updates: 'container=container-aws-console-beta,tag=${CIRCLE_SHA1}'


